export const phoneCountryCodes = [
  { code: '+93', country: 'Afghanistan' },
  { code: '+54', country: 'Argentina' },
  { code: '+61', country: 'Australia' },
  { code: '+994', country: 'Azerbaijan' },
  { code: '+973', country: 'Bahrain' },
  { code: '+880', country: 'Bangladesh' },
  { code: '+975', country: 'Bhutan' },
  { code: '+55', country: 'Brazil' },
  { code: '+1', country: 'Canada/USA' },
  { code: '+86', country: 'China' },
  { code: '+420', country: 'Czech Republic' },
  { code: '+20', country: 'Egypt' },
  { code: '+358', country: 'Finland' },
  { code: '+33', country: 'France' },
  { code: '+49', country: 'Germany' },
  { code: '+62', country: 'Indonesia' },
  { code: '+98', country: 'Iran' },
  { code: '+353', country: 'Ireland' },
  { code: '+972', country: 'Israel' },
  { code: '+39', country: 'Italy' },
  { code: '+81', country: 'Japan' },
  { code: '+7', country: 'Kazakhstan/Russia' },
  { code: '+996', country: 'Kyrgyzstan' },
  { code: '+60', country: 'Malaysia' },
  { code: '+52', country: 'Mexico' },
  { code: '+976', country: 'Mongolia' },
  { code: '+95', country: 'Myanmar' },
  { code: '+977', country: 'Nepal' },
  { code: '+31', country: 'Netherlands' },
  { code: '+64', country: 'New Zealand' },
  { code: '+92', country: 'Pakistan' },
  { code: '+63', country: 'Philippines' },
  { code: '+48', country: 'Poland' },
  { code: '+351', country: 'Portugal' },
  { code: '+974', country: 'Qatar' },
  { code: '+966', country: 'Saudi Arabia' },
  { code: '+65', country: 'Singapore' },
  { code: '+27', country: 'South Africa' },
  { code: '+82', country: 'South Korea' },
  { code: '+34', country: 'Spain' },
  { code: '+94', country: 'Sri Lanka' },
  { code: '+46', country: 'Sweden' },
  { code: '+41', country: 'Switzerland' },
  { code: '+992', country: 'Tajikistan' },
  { code: '+66', country: 'Thailand' },
  { code: '+90', country: 'Turkey' },
  { code: '+993', country: 'Turkmenistan' },
  { code: '+971', country: 'UAE' },
  { code: '+44', country: 'UK' },
  { code: '+998', country: 'Uzbekistan' },
  { code: '+84', country: 'Vietnam' }
];